### ISSUE TITLE
[Bug] Trying to type an emote that starts and ends with a : rarely crashes the chatting window.

### ISSUE THREAD

**Issue by Master-64** [SevenTV/Extension#291]
**Describe the bug**
When attempting to type any emote like : red_circle : or anything like this, the chatting window will rarely crash. To be clear, this isn't referring to the part where you view the messages, but rather where you type your messages. That and all the other visual elements below that part will disappear until you refresh the browser.

**To Reproduce**
1. Try to type any emote starting with and ending with a :
2. See error (rarely)

**Expected behavior**
Chatting window doesn't crash when attempting to display potential emotes above the chatting window

**Version:**
v2.2.3

Note: I've only personally had this glitch occur twice; it's very rare and not really feasible to reproduce on the spot.

**Comment by Cameron2920** [comment]
I can reproduce this fairly consistently after refreshing a page, and when 7TV and FFZ are enabled. Here is the error log from the console.

```
vendor-100a27dadfccf8c5a367.js:1 TypeError: Cannot read properties of undefined (reading 'key')
    at twitch.js:103:59537
    at Array.forEach (<anonymous>)
    at t.getMatches (twitch.js:103:59495)
    at t.getMatches (twitch.js:103:59456)
    at n.getMatches (pages.channel.components.channel-shell.components.chat-shell.components.chat-live-127e5d4bd2d9c2d94e36.js:1:398306)
    at n.<anonymous> (pages.channel.components.channel-shell.components.chat-shell.components.chat-live-127e5d4bd2d9c2d94e36.js:1:397356)
    at vi (vendor-100a27dadfccf8c5a367.js:1:855976)
    at cs (vendor-100a27dadfccf8c5a367.js:1:890939)
    at wc (vendor-100a27dadfccf8c5a367.js:1:908368)
    at t.unstable_runWithPriority (vendor-100a27dadfccf8c5a367.js:1:927839)
rs @ vendor-100a27dadfccf8c5a367.js:1
i.componentDidCatch.n.callback @ vendor-100a27dadfccf8c5a367.js:1
vi @ vendor-100a27dadfccf8c5a367.js:1
cs @ vendor-100a27dadfccf8c5a367.js:1
wc @ vendor-100a27dadfccf8c5a367.js:1
t.unstable_runWithPriority @ vendor-100a27dadfccf8c5a367.js:1
Ho @ vendor-100a27dadfccf8c5a367.js:1
bc @ vendor-100a27dadfccf8c5a367.js:1
ac @ vendor-100a27dadfccf8c5a367.js:1
(anonymous) @ vendor-100a27dadfccf8c5a367.js:1
t.unstable_runWithPriority @ vendor-100a27dadfccf8c5a367.js:1
Ho @ vendor-100a27dadfccf8c5a367.js:1
Yo @ vendor-100a27dadfccf8c5a367.js:1
Zo @ vendor-100a27dadfccf8c5a367.js:1
tc @ vendor-100a27dadfccf8c5a367.js:1
enqueueSetState @ vendor-100a27dadfccf8c5a367.js:1
w.setState @ vendor-100a27dadfccf8c5a367.js:1
n.onEditableValueUpdate @ pages.channel.components.channel-shell.components.chat-shell.components.chat-live-127e5d4bd2d9c2d94e36.js:1
(anonymous) @ features.chat.components.chat-input.components.wysiwyg-chat-input.component-aae676a5b7b233d9d55e.js:1
(anonymous) @ features.chat.components.chat-input.components.wysiwyg-chat-input.component-aae676a5b7b233d9d55e.js:1
setTimeout (async)
(anonymous) @ features.chat.components.chat-input.components.wysiwyg-chat-input.component-aae676a5b7b233d9d55e.js:1
ss @ vendor-100a27dadfccf8c5a367.js:1
kc @ vendor-100a27dadfccf8c5a367.js:1
t.unstable_runWithPriority @ vendor-100a27dadfccf8c5a367.js:1
Ho @ vendor-100a27dadfccf8c5a367.js:1
xc @ vendor-100a27dadfccf8c5a367.js:1
j @ vendor-100a27dadfccf8c5a367.js:1
Zt @ vendor-100a27dadfccf8c5a367.js:1
core-124efe8cb1401d76e99c.js:1 7:42:20 PM [ERROR] [error-boundary] [ChatInput] An unhandled exception occurred in the component hierarchy TypeError: Cannot read properties of undefined (reading 'key')
    at twitch.js:103:59537
    at Array.forEach (<anonymous>)
    at t.getMatches (twitch.js:103:59495)
    at t.getMatches (twitch.js:103:59456)
    at n.getMatches (pages.channel.components.channel-shell.components.chat-shell.components.chat-live-127e5d4bd2d9c2d94e36.js:1:398306)
    at n.<anonymous> (pages.channel.components.channel-shell.components.chat-shell.components.chat-live-127e5d4bd2d9c2d94e36.js:1:397356)
    at vi (vendor-100a27dadfccf8c5a367.js:1:855976)
    at cs (vendor-100a27dadfccf8c5a367.js:1:890939)
    at wc (vendor-100a27dadfccf8c5a367.js:1:908368)
    at t.unstable_runWithPriority (vendor-100a27dadfccf8c5a367.js:1:927839) {info: {…}}
```

**Comment by Cameron2920** [comment]
This issue has been bugging the heck out of me, so I've made a fix for it.

**Comment by tunacanman** [comment]
Workaround fix: Open the bttv(I think?) emote menu. The one with the circle smile emoji. Scroll/skip down to the unicode emojis so it starts loading them. Now the chat won't crash.
